[package]
name = "stable-fs"
version = "0.1.8"
edition = "2021"


[dependencies]
bitflags = "2.3.1"
ic-cdk = "0.8"
ic-stable-structures = "0.5.4"
serde = "1.0.164"
serde_bytes = "0.11"
ciborium = "0.2.1"
